---
title: 五十嵐 公一
---

# **Koichi IGARASHI**

**個人アドレス**: igapi.xxx[at]gmail.com

**学内アドレス**: igapi[at]hokudai.ac.jp

[GoogleScholar][researchmap][[twitter]](https://twitter.com/igapije) [[researchgate]](https://www.researchgate.net/profile/Koichi-Igarashi-3) [[orchid]](https://orcid.org/0000-0002-3537-9239) [[github]](https://github.com/Koichi-Igarashi)

**CV** [日本語]/[English]

### Education

|               |      |                                                           |
|---------------|------|-----------------------------------------------------------|
| 2019.4-2023.3 | 学士 | 北海道大学 水産学部 海洋生物科学科                        |
| 2023.4-       | 修士 | 北海道大学 水産科学院 海洋生物資源科学専攻 海洋生物学講座 |
|               |      |                                                           |

### Publication

1.  **Igarashi K**, Wada S. Tonic immobility in a marine isopod: the effects of body size, sex and colour morph. Journal of the Marine Biological Association of the United Kingdom. Accepted.
2.  準備中

### Presentation

1.  **五十嵐公一**・和田哲 " イソへラムシは動かない: 対捕食者行動としての不動行動とその個体間変異パターン" 2022年日本プランクトン学会・日本ベントス学会合同大会，オンライン．2022年9月 (口頭)
2.  **五十嵐公一**・和田哲 "イソへラムシは不動行動で魚類捕食者からの捕食を回避する" 2022年度日本生態学会北海道地区大会，オンライン．2022年12月 (口頭)．**若手研究奨励賞受賞**
3.  **五十嵐公一**・和田哲 "イソへラムシは動かない: 対捕食者行動としての不動行動と複数種の捕食者への反応" 第70回日本生態学会大会，オンライン．2023年3月 (ポスター)．**ポスター賞最優秀賞（行動分野) 受賞**

### Awards

-   2022年12月. 2022年度日本生態学会北海道地区会，若手研究奨励賞 受賞

-   2023年3月．第70回日本生態学会大会，ポスター賞最優秀賞（行動分野) 受賞

### Grants

-   

### Academic Societies

-   日本ベントス学会 (2022年 \~ 2023年)

-   日本生態学会 (2023年 \~)

## News

2024.01.05 ホームページを作成してみました．まだ未完成
